name: Release
on:
  release:
    types:
      - created

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, darwin, windows]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Release binaries
      uses: mcuadros/go-release-action@master
      with:
        project_path: cmd/damb
        binary_name: damb
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: amd64
